// eslint-disable-next-line no-unused-vars
export const fakeData = [
    { id: "abcde12345", date: {seconds: new Date().getSeconds(), nanoseconds: 0}, message: "Expect the best. Prepare for the worst. Capitalize on what comes.", likes: 5, dislikes: 2 },
    { id: "fghij67890", date: {seconds: new Date().getSeconds(), nanoseconds: 0}, message: "Success is the sum of small efforts, repeated day in and day out.", likes: 8, dislikes: 3 },
    { id: "klmno54321", date: {seconds: new Date().getSeconds(), nanoseconds: 0}, message: "Your future is whatever you make it, so make it a good one.", likes: 6, dislikes: 1 },
    { id: "pqrst67890", date: {seconds: new Date().getSeconds(), nanoseconds: 0}, message: "The only limit to our realization of tomorrow will be our doubts of today.", likes: 7, dislikes: 4 },
    { id: "uvwxy12345", date: {seconds: new Date().getSeconds(), nanoseconds: 0}, message: "If opportunity doesn't knock, build a door.", likes: 9, dislikes: 2 },
    { id: "zabcd67890", date: {seconds: new Date().getSeconds(), nanoseconds: 0}, message: "The best way to predict the future is to create it.", likes: 10, dislikes: 3 },
    { id: "efghi54321", date: {seconds: new Date().getSeconds(), nanoseconds: 0}, message: "Don't watch the clock; do what it does. Keep going.", likes: 6, dislikes: 1 },
    { id: "jklmn67890", date: {seconds: new Date().getSeconds(), nanoseconds: 0}, message: "Your time is limited, don't waste it living someone else's life.", likes: 8, dislikes: 2 },
    { id: "opqrs12345", date: {seconds: new Date().getSeconds(), nanoseconds: 0}, message: "It always seems impossible until it's done.", likes: 7, dislikes: 1 },
    { id: "tuvwx67890", date: {seconds: new Date().getSeconds(), nanoseconds: 0}, message: "The only way to do great work is to love what you do.", likes: 9, dislikes: 3 },
    { id: "yzabc12345", date: {seconds: new Date().getSeconds(), nanoseconds: 0}, message: "The pessimist complains about the wind; the optimist expects it to change; the realist adjusts the sails.", likes: 2, dislikes: 5 },
    { id: "defgh67890", date: {seconds: new Date().getSeconds(), nanoseconds: 0}, message: "You have enemies? Good. That means you've stood up for something, sometime in your life.", likes: 3, dislikes: 7 },
    { id: "ijklm54321", date: {seconds: new Date().getSeconds(), nanoseconds: 0}, message: "Life is what happens when you're busy making other plans.", likes: 4, dislikes: 9 },
    { id: "nopqr67890", date: {seconds: new Date().getSeconds(), nanoseconds: 0}, message: "The greatest glory in living lies not in never falling, but in rising every time we fall.", likes: 2, dislikes: 6 },
    { id: "stuvw12345", date: {seconds: new Date().getSeconds(), nanoseconds: 0}, message: "I find that the harder I work, the more luck I seem to have.", likes: 3, dislikes: 8 },
    { id: "xyzabc67890", date: {seconds: new Date().getSeconds(), nanoseconds: 0}, message: "Life is really simple, but we insist on making it complicated.", likes: 1, dislikes: 5 },
    { id: "defgh12345", date: {seconds: new Date().getSeconds(), nanoseconds: 0}, message: "I have not failed. I've just found 10,000 ways that won't work.", likes: 2, dislikes: 6 },
    { id: "ijklmn67890", date: {seconds: new Date().getSeconds(), nanoseconds: 0}, message: "Success usually comes to those who are too busy to be looking for it.", likes: 3, dislikes: 7 },
    { id: "opqrs12345", date: {seconds: new Date().getSeconds(), nanoseconds: 0}, message: "Don't be afraid to give up the good to go for the great.", likes: 1, dislikes: 4 },
    { id: "tuvwx67890", date: {seconds: new Date().getSeconds(), nanoseconds: 0}, message: "In three words I can sum up everything I've learned about life: it goes on.", likes: 2, dislikes: 6 },
    { id: "yzabc12345", date: {seconds: new Date().getSeconds(), nanoseconds: 0}, message: "You miss 100% of the shots you don't take.", likes: 0, dislikes: 0 },
    { id: "defgh67890", date: {seconds: new Date().getSeconds(), nanoseconds: 0}, message: "The only thing we have to fear is fear itself.", likes: 0, dislikes: 0 },
    { id: "ijklm54321", date: {seconds: new Date().getSeconds(), nanoseconds: 0}, message: "It does not matter how slowly you go, as long as you do not stop.", likes: 0, dislikes: 0 },
    { id: "nopqr67890", date: {seconds: new Date().getSeconds(), nanoseconds: 0}, message: "It's not whether you get knocked down, it's whether you get up.", likes: 0, dislikes: 0 },
    { id: "stuvw12345", date: {seconds: new Date().getSeconds(), nanoseconds: 0}, message: "The best revenge is massive success.", likes: 0, dislikes: 0 },
    { id: "xyzabc67890", date: {seconds: new Date().getSeconds(), nanoseconds: 0}, message: "Happiness is not something ready made. It comes from your own actions.", likes: 0, dislikes: 0 },
    { id: "defgh12345", date: {seconds: new Date().getSeconds(), nanoseconds: 0}, message: "Believe you can and you're halfway there.", likes: 0, dislikes: 0 },
    { id: "ijklmn67890", date: {seconds: new Date().getSeconds(), nanoseconds: 0}, message: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", likes: 0, dislikes: 0 },
    { id: "opqrs12345", date: {seconds: new Date().getSeconds(), nanoseconds: 0}, message: "It's not what you look at that matters, it's what you see.", likes: 0, dislikes: 0 },
    { id: "tuvwx67890", date: {seconds: new Date().getSeconds(), nanoseconds: 0}, message: "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.", likes: 0, dislikes: 0 },
];